<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet"  href="style.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">  
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    
        <title>Titre</title>
    </head>

    <body>
        <header class="header clearfix">
            <nav>
                <ul class="nav nav-pills  justify-content-center bg-dark">
                    <li class="nav-item">
                        <a class="nav-link active" href="../public/">Accueil <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="../public/showall">Recettes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="../templates/ajouter.phtml"> Ajouter</a>
                    </li>
                </ul>
            </nav>
        </header>
        <h1>Modifier une  recette</h1>
    	<form method="post" action="../public/modifier">
            <input type="hidden" name="id" id="id" value=<?php echo $plats->id?> readonly="readonly">
    		<p><label for="prenom">prenom:</label> <input type="text" class="form-control mr-sm-2" name="prenom" id="prenom" value="<?php echo $plats->prenom ?>"></p>
    		<p><label for="nom">nom:</label> <input type="text" class="form-control mr-sm-2" name="nom" id="nom" value="<?php echo $plats->nom ?>"></p>
    		<p><label for="email">email:</label> <input type="email" class="form-control mr-sm-2" name="email" id="email" value=<?php echo $plats->email ?>></p>
            <p><label for="titre">titre:</label> <textarea class="form-control mr-sm-2"  name="titre" id="titre" rows="1" cols="20"><?php echo $plats->titre ?></textarea></p>
            <p><label for="ingredient">ingredient:</label>: <textarea class="form-control mr-sm-2" name="ingredient" id="ingredient" rows="5" cols="30" ><?php echo $plats->ingredient ?></textarea></p>
    		<p><label for="recette">recette:</label> <textarea class="form-control mr-sm-2" name="recette"  id="recette" rows="5" cols="40"><?php echo $plats->recette ?>
            </textarea></p>
    		<p><input type="submit" value="valider"></p>

            <a class="btn btn-outline-success my-2 my-sm-0" href="../public/" role="button">Retourner à la page d'acccueil &raquo;</a>
    	</form>
        
        
    </body>
</html>
    