<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">  
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script> 
    
        <title>Titre</title>
    </head>

    <body>
        <header class="header clearfix">
        	<nav>
            	<ul class="nav nav-pills  justify-content-center bg-dark">
                	<li class="nav-item">
                	    <a class="nav-link active" href="../public/">Accueil <span class="sr-only">(current)</span></a>
                	</li>
                	<li class="nav-item">
                	    <a class="nav-link" href="../public/showall">Recettes</a>
                	</li>
                	<li class="nav-item">
                        <a class="nav-link active" href="../templates/ajouter.phtml"> Ajouter</a>
                    </li>
            	</ul>
        	</nav>
      	</header>
        <h1>Voici la liste des recettes des recettes</h1>

    
        <?php
        foreach($plats as $a)
        {   
            ?>
                <h1><?php echo $a->titre; ?></h1>
    			<div class="row">
        			<div class="col-lg-4">
            			<h2>Ingrédients</h2>
            			<p><p><?php echo $a->ingredient; ?></p>
            		</div>
        			<div class="col-lg-4">
            			<h2>La recette</h2>
            			<p class="recetteall"><?php echo $a->recette; ?> </p></br>
            			<tr >
                    		Auteur: <td><span class="iden"><?php echo $a->nom; ?></span></td>
                    		<td class="iden"><span class="iden"><?php echo $a->prenom; ?></span></td></br>
                    		E-mail: <td><span class="iden"><?php echo $a->email; ?></span></td>
                    	</tr>
        			</div>
        			<div>
        				<td>
        					<form method="post" action="../public/amodifier">
                        		<input type="hidden" name="id" id="id" value=<?php echo $a->id ?> readonly="readonly">
                        		<p><input type="submit" class="btn btn-primary" value="Modifier"></p>
                    		</form>
                    		<form method="post" action="../public/supprimer">
                        		<input type="hidden" name="id" id="id" value=<?php echo $a->id ?> readonly="readonly">
                        		<p><input type="submit" class="btn btn-primary" value="Supprimer"></p>
                    		</form>
                    		<form method="post" action="../public/showone">
                        		<input type="hidden" name="id" id="id" value=<?php echo $a->id ?> readonly="readonly">
                        		<p><input type="submit" class="btn btn-primary" value="Observer seul"></p>
                    		</form>
                    	</td>
    				</div>
    			</div>
            <?php
        }

        ?>
   		<p><a class="btn btn-outline-success my-2 my-sm-0" href="/Web/public/" role="button">Retourner à la page d'accueil &raquo;</a></p>
