<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet"  href="style.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">  
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    
        <title>Titre</title>
    </head>

    <body>
        <header class="header clearfix">
            <nav>
                <ul class="nav nav-pills  justify-content-center bg-dark">
                    <li class="nav-item">
                        <a class="nav-link active" href="../public/">Accueil <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="../public/showall">Recettes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="../templates/ajouter.phtml"> Ajouter</a>
                    </li>
                </ul>
            </nav>
        </header>
        <h1><?php echo $plats->titre; ?></h1>
        <div class="row">
            <div class="col-lg-4">
                <h2>Ingrédients</h2>
                <p><p><?php echo $plats->ingredient; ?> </p>
            
            </div>
            <div class="col-lg-4">
                <h2>La recette</h2>
                <p class="recetteall"><?php echo $plats->recette; ?> </p></br>
                <tr >
                    Auteur: <td><span class="iden"><?php echo $plats->nom; ?></span></td>
                            <td class="iden"><span class="iden"><?php echo $plats->prenom; ?></span></td></br>                                
                    E-mail: <td><span class="iden"><?php echo $plats->email; ?></span></td>
                </tr>
            </div>
        </div>
        <p><a class="btn btn-outline-success my-2 my-sm-0" href="../public/" role="button">Retourner à la page d'accueil &raquo;</a></p>
    </body>
</html>